version: '3.3'

services:
 rover:
  build:
   context: ./rover
  ports:
   - 3000:3000
  environment:
   - SERVER_PORT=3000

 rover-ui:
  build:
   context: ./rover-ui
  ports:
   - 8000:8000
  volumes:
   - ./rover-ui/src:/app/src

#  server-node:
#   build:
#    context: ./backend-node
#   ports:
#    - 8081:8081
#   volumes:
#    - ./backend-node/src:/app/src

 rover-manager-api:
  hostname: rover-manager-api
  command: flask run --host 0.0.0.0 --port 8081
  environment:
    - FLASK_APP=apps.commands:app
  build:
    context: ./rover-manager
  ports:
    - 8081:8081
  volumes:
    - ./rover-manager:/app


 rover-manager-tasks:
  hostname: rover-manager-tasks
  command: python -m apps.commands_processor
  build:
    context: ./rover-manager
  volumes:
    - ./rover-manager:/app

# server-mojo:
#  build:
#   context: ./perl-mojolicious
#  ports:
#   - 8081:8081
#  volumes:
#   - ./perl-mojolicious:/usr/src/app

 redis:
  image: redis
  container_name: mars_redis
  hostname: mars-redis
  restart: always
  ports:
    - 127.0.0.1:6380:6379